server:
  port: 8081
spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.41:3306/user?serverTimezone=UTC&characterEncoding=UTF8
#    hikari:
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      maximum-pool-size: 20
#      read-only: true
  application:
    name: user-center
    main:
      allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 106.13.81.68:8848
  redis:
    redisson:
      config: classpath:redisson.yaml